# -*- coding: utf-8 -*-
"""Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BbfiSxrpmL7tnUJGQzDtLDk0zK9FEbgV
"""

import pandas as pd
import os
import numpy as np
import json

def get_attack_label(filename):
    attack_mapping = {
        "correlated_signal_attack": 1,
        "correlated_signal_attack_masquerade": 2,
        "fuzzing_attack": 3,
        "max_engine_coolant_temp_attack": 4,
        "max_engine_coolant_temp_attack_masquerade": 5,
        "max_speedometer_attack": 6,
        "max_speedometer_attack_masquerade": 7,
        "reverse_light_off_attack": 8,
        "reverse_light_off_attack_masquerade": 9,
        "reverse_light_on_attack": 10,
        "reverse_light_on_attack_masquerade": 11
    }

    # Strip any trailing '_N' where N is a digit, or '_N_masquerade'
    # Examples:
    # correlated_signal_attack_1 -> correlated_signal_attack
    # correlated_signal_attack_1_masquerade -> correlated_signal_attack_masquerade
    name = filename
    for i in range(1, 10):
        name = name.replace(f"_{i}_masquerade", "_masquerade")
        if name.endswith(f"_{i}"):
            name = name[:-2]

    return attack_mapping.get(name, 0)

def parse_log_file(filepath):
    """Reads a log file and returns it as a DataFrame."""
    data_list = []
    with open(filepath, "r") as fp:
        for line in fp:
            tokens = line.split()
            if len(tokens) < 3:
                continue

            # format: (timestamp) interface id#data
            # e.g. (1000000000.000000) can0 20E#4E2003A0C63F8FFF
            id_data = tokens[2].split("#")
            if len(id_data) != 2:
                continue

            id_hex, data_hex = id_data

            # Pad data with zeros to 16 chars (8 bytes) if shorter
            data_hex = data_hex.ljust(16, "0")

            csv_line = [
                float(tokens[0][1:-1]),
                int(id_hex, 16),
                int(data_hex[0:2], 16),
                int(data_hex[2:4], 16),
                int(data_hex[4:6], 16),
                int(data_hex[6:8], 16),
                int(data_hex[8:10], 16),
                int(data_hex[10:12], 16),
                int(data_hex[12:14], 16),
                int(data_hex[14:16], 16),
            ]
            data_list.append(csv_line)

    df = pd.DataFrame(data_list, columns=[
        "timestamp", "ID", "DATA0", "DATA1", "DATA2", "DATA3",
        "DATA4", "DATA5", "DATA6", "DATA7"
    ])
    return df

def generate_multi_label_dataset():
    if not os.path.exists("csv/"):
        os.mkdir("csv/")

    metadata_path = "/content/drive/MyDrive/CAN-IDS/Dataset/road/attacks/capture_metadata.json"
    if not os.path.exists(metadata_path):
        # Setup path fallback
        metadata_path = "/content/drive/MyDrive/CAN-IDS/Dataset/road/attacks/capture_metadata.json"

    try:
        with open(metadata_path, 'r') as f:
            metadata = json.load(f)
    except FileNotFoundError:
        print(f"Could not find {metadata_path}. Make sure you are in the correct directory.")
        return

    full_df = pd.DataFrame()

    attacks_dir = "/content/drive/MyDrive/CAN-IDS/Dataset/road/attacks/" if os.path.exists("attacks/") else "/content/drive/MyDrive/CAN-IDS/Dataset/road/attacks/"

    if os.path.exists(attacks_dir):
        for file in os.listdir(attacks_dir):
            if file.endswith(".log") and not file.startswith("accelerator_attack_"):
                filename = file[:-4]
                print(f"Parsing and labelling {filename} ...")
                filepath = os.path.join(attacks_dir, file)
                df = parse_log_file(filepath)

                df["label"] = 0

                if filename in metadata:
                    meta = metadata[filename]
                    attack_label = get_attack_label(filename)

                    if attack_label > 0:
                        start_time = df["timestamp"].values[0]
                        interval = meta["injection_interval"]
                        injection_id = meta["injection_id"]
                        injection_data = meta["injection_data_str"]

                        if interval is not None:
                            # Time bounds
                            condition = (df["timestamp"] >= start_time + interval[0]) & \
                                        (df["timestamp"] <= start_time + interval[1])

                            # ID bound
                            if injection_id and "XXX" not in injection_id:
                                inj_id_int = int(injection_id, 16)
                                condition = condition & (df["ID"] == inj_id_int)

                            # Data bounds
                            if injection_data:
                                for i in range(8):
                                    byte_str = injection_data[i * 2: i * 2 + 2]
                                    if "XX" not in byte_str:
                                        condition = condition & (df[f"DATA{i}"] == int(byte_str, 16))

                            df.loc[condition, "label"] = attack_label

                full_df = pd.concat([full_df, df], ignore_index=True)

    ambient_dir = "/content/drive/MyDrive/CAN-IDS/Dataset/road/ambient/" if os.path.exists("/content/drive/MyDrive/CAN-IDS/Dataset/road/ambient/") else "/content/drive/MyDrive/CAN-IDS/Dataset/road/ambient/"
    if os.path.exists(ambient_dir):
        for file in os.listdir(ambient_dir):
            if file.endswith(".log"):
                filename = file[:-4]
                print(f"Reading {file} from ambient folder ...")
                filepath = os.path.join(ambient_dir, file)
                df = parse_log_file(filepath)
                df["label"] = 0
                full_df = pd.concat([full_df, df], ignore_index=True)

    print("Saving full multi-label dataset to csv/road_multi_label.csv ...")
    full_df.to_csv("/content/drive/MyDrive/CAN-IDS/Dataset/csv/road_multi_label.csv", index=False)
    print("Done!")

if __name__ == "__main__":
    generate_multi_label_dataset()

!mkdir /content/drive/MyDrive/CAN-IDS/Dataset/csv



import pandas as pd

df03=pd.read_csv("/content/drive/MyDrive/CAN-IDS/Dataset/csv/road_multi_label.csv")

df03['label'].unique()

df03['label'].value_counts()